
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl RtpsRelayNodeLib
// ------------------------------
#ifndef RTPSRELAYNODELIB_EXPORT_H
#define RTPSRELAYNODELIB_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (RTPSRELAYNODELIB_HAS_DLL)
#  define RTPSRELAYNODELIB_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && RTPSRELAYNODELIB_HAS_DLL */

#if !defined (RTPSRELAYNODELIB_HAS_DLL)
#  define RTPSRELAYNODELIB_HAS_DLL 1
#endif /* ! RTPSRELAYNODELIB_HAS_DLL */

#if defined (RTPSRELAYNODELIB_HAS_DLL) && (RTPSRELAYNODELIB_HAS_DLL == 1)
#  if defined (RTPSRELAYNODELIB_BUILD_DLL)
#    define RtpsRelayNodeLib_Export ACE_Proper_Export_Flag
#    define RTPSRELAYNODELIB_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define RTPSRELAYNODELIB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* RTPSRELAYNODELIB_BUILD_DLL */
#    define RtpsRelayNodeLib_Export ACE_Proper_Import_Flag
#    define RTPSRELAYNODELIB_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define RTPSRELAYNODELIB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* RTPSRELAYNODELIB_BUILD_DLL */
#else /* RTPSRELAYNODELIB_HAS_DLL == 1 */
#  define RtpsRelayNodeLib_Export
#  define RTPSRELAYNODELIB_SINGLETON_DECLARATION(T)
#  define RTPSRELAYNODELIB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* RTPSRELAYNODELIB_HAS_DLL == 1 */

// Set RTPSRELAYNODELIB_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (RTPSRELAYNODELIB_NTRACE)
#  if (ACE_NTRACE == 1)
#    define RTPSRELAYNODELIB_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define RTPSRELAYNODELIB_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !RTPSRELAYNODELIB_NTRACE */

#if (RTPSRELAYNODELIB_NTRACE == 1)
#  define RTPSRELAYNODELIB_TRACE(X)
#else /* (RTPSRELAYNODELIB_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define RTPSRELAYNODELIB_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (RTPSRELAYNODELIB_NTRACE == 1) */

#endif /* RTPSRELAYNODELIB_EXPORT_H */

// End of auto generated file.
